name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - shell: bash
      env:
        REPO_PASS: ${{ secrets.PYPI }}
        VERSION_TAG: ${{ github.event.release.tag_name }}
        BRANCH: ${{ github.event.release.target_commitish }}
      run: |
        VERSION=$(echo "${VERSION_TAG}" | cut -c2-) make build
        make publish

        # Setup git
        # https://api.github.com/users/github-actions%5Bbot%5D
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Commit and push updated release files
        git checkout -b "${BRANCH}"
        git add .
        git commit -m "Update release version to ${VERSION_TAG}"
        git push origin "${BRANCH}"

        git tag --force "${VERSION_TAG}"
        git push --force origin "${VERSION_TAG}"
